### ISSUE TITLE
Wrong value for `radconst` in quality_statistics function

### ISSUE THREAD

**Issue by Tastaturtaste** [libigl/triangle#7]
https://github.com/libigl/triangle/blob/3ee6cac2230f0fe1413879574f741c7b6da11221/triangle.cpp#L15411

While browsing the code I saw that the variable `radconst` does get initialized with PI / 18.0, which I suppose should probably be PI / 180.0.

I apologize if my assumption is wrong.

**Comment by qnzhou** [comment]
I think it may not be a typo.  Triangle computes the angle histogram of the output.  Each bin is 10 degrees wide, which corresponds to `radconst`.

**Comment by Tastaturtaste** [comment]
Ok, thanks for clearing it up. The use of the variable was not clear to me.
